version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: general
      POSTGRES_PASSWORD: passsecret
      POSTGRES_DB: resto
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - projhouse-net

  web:
    build: .
    restart: always
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - db
    command: >
      sh -c "alembic upgrade head &&
             uvicorn src.main:main_app --host 0.0.0.0 --port 8000"
    networks:
      - projhouse-net

  nginx:
    image: nginx:stable
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - /home/deploy/myhouseproject/front/dist:/usr/share/nginx/html:ro
    depends_on:
      - web
    networks:
      - projhouse-net
    command: >
      sh -c "
      until nc -z web 8000; do
        echo 'Waiting for FastAPI...';
        sleep 2;
      done;
      nginx -g 'daemon off;'
      "

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "trap exit TERM;
      while :; do
        sleep 12h & wait $${!};
        certbot renew --webroot -w /var/www/certbot --quiet --deploy-hook 'nginx -s reload';
      done"
    networks:
      - projhouse-net

volumes:
  db_data:

networks:
  projhouse-net:
